version: '3.8'

services:
  web:
    build:
      context: ../..
      dockerfile: apps/web/Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    environment:
      # Node and Server Config
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=3000
      - HOSTNAME=0.0.0.0

      # API URL (use service name 'api' for internal Docker communication by default)
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://api:3001}

    ports:
      - "3000:3000"
    labels:
      - coolify.managed=true
      - traefik.enable=true
      - "traefik.http.routers.web.rule=Host(`${SERVICE_FQDN_WEB}`)"
      - traefik.http.routers.web.entryPoints=http