version: '3.8'

services:
  web:
    build:
      context: ../..
      dockerfile: apps/web/Dockerfile
      args:
        - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
    environment:
      # Node and Server Config
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=3000
      - HOSTNAME=0.0.0.0

      # API URL (use service name 'api' for internal Docker communication by default)
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://api:3001}

    ports:
      - "3000:3000"
    labels:
      - coolify.managed=true
      - traefik.enable=true
      - "traefik.http.routers.web.rule=Host(`${SERVICE_FQDN_WEB}`)"
      - traefik.http.routers.web.entryPoints=http
    depends_on:
      - api

  api:
    build:
      context: ../..
      dockerfile: apps/api/Dockerfile
    environment:
      # Node and Server Config
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=3001
      - SKIP_ENV_VALIDATION=${SKIP_ENV_VALIDATION:-true}

      # Database
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_NAME=${DATABASE_NAME}

      # Authentication
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - CLERK_PUBLISHABLE_KEY=${CLERK_PUBLISHABLE_KEY}

      # Pterodactyl Panel
      - PTERO_URL=${PTERO_URL}
      - PTERO_APP_TOKEN=${PTERO_APP_TOKEN}
      - PTERO_CLIENT_TOKEN=${PTERO_CLIENT_TOKEN}

      # DNS and CDN
      - BUNNY_DNS_API_KEY=${BUNNY_DNS_API_KEY}
      - CLOUDFLARE_ACCOUNT_ID=${CLOUDFLARE_ACCOUNT_ID}
      - CLOUDFLARE_ACCESS_KEY_ID=${CLOUDFLARE_ACCESS_KEY_ID}
      - CLOUDFLARE_ACCESS_KEY=${CLOUDFLARE_ACCESS_KEY}
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}

      # Email
      - RESEND_API_KEY=${RESEND_API_KEY}

      # Payments
      - STRIPE_API_KEY=${STRIPE_API_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - PRO_STRIPE_PRICE_ID=${PRO_STRIPE_PRICE_ID}

      # Redis
      - UPSTASH_REDIS_URL=${UPSTASH_REDIS_URL}
      - UPSTASH_REDIS_TOKEN=${UPSTASH_REDIS_TOKEN}

      # Misc
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - BESZEL_PASSWORD=${BESZEL_PASSWORD}
      - BESZEL_EMAIL=${BESZEL_EMAIL}

    ports:
      - "3001:3001"
    labels:
      - coolify.managed=true
      - traefik.enable=true
      - "traefik.http.routers.api.rule=Host(`${SERVICE_FQDN_API}`)"
      - traefik.http.routers.api.entryPoints=http