[phases.setup]
    # https://github.com/NixOS/nixpkgs/commits/master/pkgs/development/web/bun/default.nix
    nixpkgsArchive = '6fe4a66c78e3eb7d6fe13fe8d205ea4ff17dce55' # https://github.com/NixOS/nixpkgs/commit/d05592ea7e9656648093dfe0e817819486bd5054